### ISSUE TITLE
New debug commands

### ISSUE THREAD

**Issue by Kerie70** [zippity21/Stardew_Valley_Regression_Mod#22]
Updated to newest release and the new debug commands do not seem to be working.  I've also noticed that you have both increase and decrease incontinence set to the exact same key bindings.  Left Alt + W both raises and lowers at the same time?

**Comment by zippity21** [comment]
I fixed the documentation, thanks for finding that.

The commands themselves seem to be working though. A few things to keep in mind:

1. Make sure you're in debug mode by pressing F9. You'll see the additional Bladder and bowel bars (assuming you have them enabled in config.json)
2. While you'll get messages as your continence decreases, you don't get any as you increase. Though that is something I thought about adding.

Is there more detail you can provide about what you expect to see vs what you are seeing?
