### ISSUE TITLE
Sprite related

### ISSUE THREAD

**Issue by YOISTAR** [zippity21/Stardew_Valley_Regression_Mod#34]
![image](https://user-images.githubusercontent.com/92817449/140661932-806c1fb3-054d-4380-9353-979a8d038efc.png)
Just wondering whether the sprite is missing, or hasn't been made yet. Any response is appreciated. 

EDIT: Noticed that it was an indicator that keeps filling up, the clean square threw me off.  (noticed the edges had like 3 squares filled up too)

**Comment by zippity21** [comment]
So, are you all set?
