### ISSUE TITLE
1.2.2 - Underwear/Diaper Icon Covered by Journal Icon

### ISSUE THREAD

**Issue by LilBearBlue** [zippity21/Stardew_Valley_Regression_Mod#44]
![Capture](https://user-images.githubusercontent.com/93164132/141967253-659c2d8c-5930-4863-a7ea-05ff70a96fb9.JPG)

Only started happening after patching into the most recent update. Guessing as a result of the sprite changes? Setting UI Scale or Zoom to 95% gets it properly visible.

Resolution: 2560x1440
Window Mode: Windowed (also happens in Borderless and Fullscreen)
UI Scale and Zoom: 100%

Edit: Seems like it may impact the hunger/thirst bars as well, but only in combat zones such as the mines, ginger island volcano, etc.

![Capture](https://user-images.githubusercontent.com/93164132/141971764-673911f4-3225-4c8a-b5b6-cf15f668c277.JPG)

**Comment by zippity21** [comment]
Oof. Okay. That is almost certainly an issue with the rewritten drawing code. This is why we can't have nice things (I break them).

Thank you for the report. I'll update here when I think I have a fix

**Comment by zippity21** [comment]
Issue should be resolved as of release v1.2.4
