### ISSUE TITLE
Disabling Hunger and thirst disables bladder and bowels

### ISSUE THREAD

**Issue by DBCA1998** [zippity21/Stardew_Valley_Regression_Mod#46]
So ive disable hunger and thirst as they seem to lower quite fast and food doesnt feel up the hunger meter enougth aftyer eating leaving me stuck without money and food.
But the problem is it seems to continue to function in debug mode and once the meters hit 0 the bowels and bladders stop filling up too. and the only way to fill it up is in debog mode. 
I know its not a huge issue but its kinda annoying so i put it up. 

PS: any way to change hunger and thirst usage? or to increase how much you get from foods?

**Comment by zippity21** [comment]
I've been trying to rebalance the bladder/bowel/food/water, but haven't hit the sweet spot yet.

As for the bladder and bowel not filling once hunger and thirst are depleted, is the idea that if you're dehydrated you won't really need to pee, and if you're not taking in food, you won't need to poo.

Agreed that it still needs some work.

**Comment by zippity21** [comment]
To address the problem state in the title itself; the problem where bladders/bowels aren't filling when hunger/thirst are disabled should be fixed as of release v1.2.4. Go ahead and try it out and let me know if it resolves your issue.

**Comment by zippity21** [comment]
Based on lack of response, I assume the issue has been resolved.
