### ISSUE TITLE
Can't See Meters and Diaper Indicator

### ISSUE THREAD

**Issue by OriginCosdenex15** [zippity21/Stardew_Valley_Regression_Mod#47]
So I was just playing like normal and suddenly they Bladder and Bowel meters as well as the Diaper Indicator just wouldn't show up no matter what I did if I even tried reinstalling the mod.

**Comment by zippity21** [comment]
Very odd. Did this happen in any particular location, or during an event? Are you full-screen or windowed? What resolution, and what UI scale?

Could you share your save file?

Just need to figure out how to reproduce, so I can debug.

**Comment by OriginCosdenex15** [comment]
Ok but I would have to send the mod pack so that it works

**Comment by OriginCosdenex15** [comment]
I will send it after I'm done with work.

**Comment by OriginCosdenex15** [comment]
I installed the newest version and it seems to be working properly again.

**Comment by zippity21** [comment]
Excellent! Please report any other issues you find, and I'll do my best to resolve them.
