### ISSUE TITLE
Leo ends up Softlocking

### ISSUE THREAD

**Issue by Miku-Nozomu** [zippity21/Stardew_Valley_Regression_Mod#51]

**Comment by Miku-Nozomu** [comment]
Whenever I end up wetting or messing in Leo’s hut on ginger island, stardew will softlock. While I was able to use debug by turning off hunger and thirst does work but only temporarily as entering back in with that of hunger & thirst more accurately either wetting &/or messing before the next day will result in said softlock once more. It might be because that Leo is classified as a Kid just like Vincent and Jas.

**Comment by zippity21** [comment]
This sounds like something that would've been introduced in the most recent release since the default children lines were removed. I believe you are likely correct that this softlock is due to Leo not having appropriate dialogue.
